services:
  cockroach1:
    image: cockroachdb/cockroach:v23.2.11
    container_name: crdb-nodo1
    hostname: crdb-nodo1
    command:
      - start-single-node
      - --insecure
      - --accept-sql-without-tls
      - --advertise-addr=crdb-nodo1:26257
      - --http-addr=0.0.0.0:8080
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach1:/cockroach/cockroach-data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

volumes:
  cockroach1:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge
