version: '3.8'

services:
  evento-service:
    build: .
    container_name: evento-service
    ports:
      - "3002:3002"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - cockroach
      - rabbitmq
    restart: unless-stopped

  cockroach:
    image: cockroachdb/cockroach:v23.1.11
    command: start-single-node --insecure
    container_name: cockroach
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Para apps
      - "15672:15672"   # Web UI
    restart: unless-stopped

volumes:
  cockroach-data:
