# Imagen base oficial de Node.js
FROM node:20-alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar solo los archivos necesarios para instalar dependencias
COPY package*.json ./

# Instalar dependencias (usa --production si no necesitas devDependencies)
RUN npm install

# Copiar el resto del código fuente
COPY . .

# Exponer el puerto en el que se ejecutará el servicio
EXPOSE 3002

# Comando por defecto para arrancar el servicio
CMD ["node", "server.js"]
