services:
  evento-service:
    build: .
    container_name: evento-service
    ports:
      - "3002:3002"
    env_file:
      - .env
    depends_on:
      - cockroach
      - rabbitmq
    networks:
      - app-network

  cockroach:
    image: cockroachdb/cockroach:v23.1.11
    command: start-single-node --insecure
    container_name: cockroach
    ports:
      - "26259:26259"
      - "8090:8090"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmqEventos
    ports:
      - "5673:5673"
      - "15673:15673"
    networks:
      - app-network

volumes:
  cockroach-data:

networks:
  app-network:
    driver: bridge