version: '3.8'

services:
  entrada-service:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - cockroach
      - rabbitmq
    env_file:
      - .env.docker

  cockroach:
    image: cockroachdb/cockroach:v23.1.11
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  cockroach-data:
